### ISSUE TITLE
README is inaccurate

### ISSUE THREAD

**Issue by MisterMartin** [paul-shannon/slexil2#1]
The preliminary results referenced at pshannon.net are not from Dante's Inferno.

**Comment by paul-shannon** [comment]
Thanks! - I’ll check that out, make the fix.

**Comment by paul-shannon** [comment]
Hi @MisterMartin,

The pshannon.net link, unless I got the wrong one, is to https://pshannon.net/inferno/
When clicked, this is what I see:
![image](https://user-images.githubusercontent.com/2480712/236962986-97c23c8c-0861-447d-8b1d-03f62ccb02a3.png)

You must see something different!  What do you see?

**Comment by paul-shannon** [comment]
could not find confirm Charlie's finding.
